"""Add vector_id column to slack messages

Revision ID: f879e955ad3d
Revises: cc1d1143315f
Create Date: 2023-08-07 18:35:29.656787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f879e955ad3d'
down_revision = 'cc1d1143315f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_messages', schema=None) as batch_op:
        batch_op.drop_column('vector_id')

    # ### end Alembic commands ###
